# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 12b482970540f466ee4e0bdfd182a3b5f4b75c138e9f866da2056e867ec6e0e6f2e9822f2a8563066e327e52e58b1faaf58de8aa7334ea8a2c444ec8a44b689f

test:
  secret_key_base: 009697a1a1dd5febdc5daa977d57dd8814ad28f835a26cb0723b447a56bcf9f9efe8fca35a29292d6b39e2cd87615092263fe9636faf8cc934990e0c48abd17e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
